 const tempData = [ { notes: 'Hack Reactor Alumni work here',
    phone: '555-555-5555',
    email: 'Jean.peopleTeam@google.com',
    website: 'https://careers.google.com/teams/people/',
    Position: 'Full-Stack Web Developer',
    currentStep: 'Create Cover Letter',
    nextStep: 'Send in Application',
    rating: 7,
    company: 'Leannon - Olson',
    dueDate: '2020-06-09',
    jobId: 1,
    contact: 'Graham Oberbrunner' },
  { notes: 'Hack Reactor Alumni work here',
    phone: '555-555-5555',
    email: 'Jean.peopleTeam@google.com',
    website: 'https://careers.google.com/teams/people/',
    Position: 'Full-Stack Web Developer',
    currentStep: 'Create Cover Letter',
    nextStep: 'Send in Application',
    rating: 6,
    dueDate: '2020-06-09',
    jobId: 2,
    company: 'Hansen Inc',
    contact: 'Niko Hartmann' },
  { notes: 'Hack Reactor Alumni work here',
    phone: '555-555-5555',
    email: 'Jean.peopleTeam@google.com',
    website: 'https://careers.google.com/teams/people/',
    Position: 'Full-Stack Web Developer',
    currentStep: 'Create Cover Letter',
    nextStep: 'Send in Application',
    rating: 6,
    dueDate: '2020-06-09',
    jobId: 3,
    company: 'Fritsch, Monahan and Klein',
    contact: 'Hank Christiansen' },
  { notes: 'Hack Reactor Alumni work here',
    phone: '555-555-5555',
    email: 'Jean.peopleTeam@google.com',
    website: 'https://careers.google.com/teams/people/',
    Position: 'Full-Stack Web Developer',
    currentStep: 'Create Cover Letter',
    nextStep: 'Send in Application',
    rating: 2,
    dueDate: '2020-06-09',
    jobId: 4,
    company: 'Oberbrunner, Littel and MacGyver',
    contact: 'Dr. Pat Ryan' },
  { notes: 'Hack Reactor Alumni work here',
    phone: '555-555-5555',
    email: 'Jean.peopleTeam@google.com',
    website: 'https://careers.google.com/teams/people/',
    Position: 'Full-Stack Web Developer',
    currentStep: 'Create Cover Letter',
    nextStep: 'Send in Application',
    dueDate: '2020-06-09',
    jobId: 5,
    rating: 6,
    company: 'Stokes - Raynor',
    contact: 'Raina Wilkinson' } ]

    module.exports = { tempData }